# Generated by Django 4.2.7 on 2023-11-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_eco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_time', models.TextField()),
                ('end_time', models.TextField()),
                ('menu_name', models.TextField()),
                ('price', models.TextField()),
                ('address', models.TextField()),
                ('lat', models.TextField()),
                ('lon', models.TextField()),
                ('desc', models.TextField()),
                ('tags', models.TextField()),
            ],
        ),
    ]
