# Generated by Django 4.2.7 on 2023-11-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_eco', '0004_alter_store_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='tags',
        ),
    ]
