# Generated by Django 4.2.7 on 2023-11-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_eco', '0006_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
